# Generated by Django 3.1.2 on 2020-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('Latitude', models.FloatField(help_text='Latitude Y')),
                ('Longtitude', models.FloatField(help_text='Longitude X')),
                ('Unique_squirrel_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('Shift', models.CharField(blank=True, choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Shift of squirrel', max_length=10)),
                ('Date', models.DateField(blank=True, help_text='Date find the squirrel')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Is the squirrel child or adult?', max_length=15)),
                ('Primary_fur_color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], help_text='The primary color of the squirrel fur', max_length=15)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Where is the squirrel found?', max_length=20)),
                ('Specific_location', models.TextField(blank=True)),
                ('Running', models.BooleanField(help_text='Is the squirrel running?')),
                ('Chasing', models.BooleanField(help_text='Is the squirrel chasing?')),
                ('Climbing', models.BooleanField(help_text='Is the squirrel climbing?')),
                ('Eating', models.BooleanField(help_text='Is the squirrel eating?')),
                ('Foraging', models.BooleanField(help_text='Is the squirrel foraging?')),
                ('Other_activities', models.TextField(blank=True)),
                ('Kuks', models.BooleanField(help_text='Does the squirrel make kuks sound?')),
                ('Quaas', models.BooleanField(help_text='Does the squirrel make quaas sound?')),
                ('Moans', models.BooleanField(help_text='Does the squirrel moan?')),
                ('Tail_flags', models.BooleanField(help_text='Does the squirrel display tail flags?')),
                ('Tail_twitches', models.BooleanField(help_text='Does the squirrel display tail twitches?')),
                ('Approaches', models.BooleanField(help_text='Does the squirrel approach humans?')),
                ('Indifferent', models.BooleanField(help_text='Is the squirrel indifferent to human presence?')),
                ('Runs_from', models.BooleanField(help_text='Does the squirrel run away when seeing humans?')),
            ],
        ),
    ]
