# Generated by Django 3.1.2 on 2020-10-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Longtitude',
            new_name='Longitude',
        ),
    ]
