# Generated by Django 3.1.2 on 2020-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201018_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(help_text='Was the squirrel seen approaching humans?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(help_text='Was the squirrel seen chasing?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(help_text='Was the squirrel seen climbing?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(help_text='Was the squirrel seen eating?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(help_text='Was the squirrel seen foraging?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(help_text='Was the squirrel indifferent to human presence?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(help_text='Did the squirrel make kuks sound?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(help_text='E.g. 40.79408239'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(help_text='E.g. -73.95613449'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(help_text='Did the squirrel moan?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_fur_color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], help_text='Select from the list, or type the color if not in the list', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(help_text='Did the squirrel make quaas sound?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(help_text='Was the squirrel seen running?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(help_text='Was the squirrel running away when seeing humans?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('PM', 'PM'), ('AM', 'AM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(help_text='Was the squirrel seen flagging its tail?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(help_text='Was the squirrel seen wtitching its tail?'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_squirrel_id',
            field=models.CharField(default=None, help_text='E.g. 37F-PM-1014-03', max_length=20, primary_key=True, serialize=False),
        ),
    ]
